language: node_js
node_js:
  '10'
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
install:
  - npm install
script:
  - npm run clean
  - npm run build
  - npm test
after_success:
  # run code coverage
  - nyc report --reporter=lcov > coverage.lcov && codecov --token=524e2bbc-59c4-4aa2-9a64-94642802b8e1
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
